#!/usr/bin/bash
#
# Copyright (c) 2023,2025 Robert Di Pardo
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
#
ENTITIES="$(dirname "$0")/HTMLTag-entities.ini"
EXCLUSIONS='(AMP|bne|bsol|colon|COPY|commat|DD|dollar|ENG|equals|ETH|excl|fjlig|GT|lpar|LT|NewLine|nvgt|nvlt|period|QUOT|quest|REG|rpar|sol|Tab|THORN|TRADE)'

cat<<-INI > $ENTITIES
[HTML 5]
; Generated by $(jq --version), $(date +'%Y-%m-%d %H:%M')
;
$(curl -sL 'https://www.w3.org/TR/html5/entities.json' | jq --arg excl "$EXCLUSIONS" -r '
. as $ents
| keys[]
| select(index(";") and (test("^&\($excl);$") | not)) as $e
| $ents[$e].codepoints
| unique
| map("\($e[1:-1])=\(tostring)")[]')

[Emoji]
$(curl -sL 'https://api.github.com/emojis' | jq -r '
# https://rosettacode.org/wiki/Non-decimal_radices/Convert#jq
# GNU Free Document License 1.3
def to_i(base):
  explode
  | reverse
  | map(if . > 96 then . - 87 else . - 48 end)  # "a" ~ 97 => 10 ~ 87
  | reduce .[] as $c
      # state: [power, ans]
      ([1,0]; (.[0] * base) as $b | [$b, .[1] + (.[0] * $c)])
  | .[1];
. as $ents
| keys[]
| select(length > 1) as $e
| $ents[$e]
| select(test("\\/unicode\\/"))
| split("/").[-1]
| capture("(?<codept>[a-f0-9]+)","i").codept
| "\($e)=\(to_i(16))"')

[XML]
; C0 Controls and Basic Latin
quot=34			; quotation mark, U+0022 ISOnum
amp=38			; ampersand, U+0026 ISOnum
lt=60			; less-than sign, U+003C ISOnum
gt=62			; greater-than sign, U+003E ISOnum
apos=39			; apostrophe = APL quote, U+0027 ISOnum
INI
