version: 2.1
#
# Copyright (c) 2023,2024 Robert Di Pardo <dipardo.r@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
#
orbs:
  win: circleci/windows@5

references:
  executor: &executor
    executor:
      name: win/default
  development: &development
    filters:
      tags:
        only: /v.*/
  production: &production
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /v.*/

parameters:
  plugin-name:
    type: string
    default: HTMLTag

jobs:
  build:
    <<: *executor
    environment:
      VisualStudioVersion: '17.0'
    steps:
      - checkout
      - run:
          name: Install CMake
          command: |
            choco install python -y
            refreshenv
            python -m pip install cmake~=3.30.0
            cmake --version
      - run:
         name: Install the v141_xp VC toolset
         command: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer"
           .\vs_installer.exe modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Community" `
            --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 `
            --add Microsoft.VisualStudio.Component.WinXP `
            --downloadThenInstall --quiet
      - run:
         name: Build and Pack
         command: make_release.cmd
         shell: cmd.exe
      - unless:
          condition:
            matches:
              pattern: 'v.*'
              value:   << pipeline.git.tag >>
          steps:
            - run:
               name: Prepare Artifacts
               command: |
                 7z a -tzip << pipeline.parameters.plugin-name >>_x64.zip ./dat/*.ini ./out/x64/Release/<< pipeline.parameters.plugin-name >>.dll
                 7z a -tzip << pipeline.parameters.plugin-name >>_win32.zip ./dat/*.ini ./out/Win32/Release/<< pipeline.parameters.plugin-name >>_unicode.dll
                 7z a -tzip << pipeline.parameters.plugin-name >>_arm64.zip ./dat/*.ini ./out/ARM64/Release/<< pipeline.parameters.plugin-name >>.dll
            - store_artifacts:
                name: Upload << pipeline.parameters.plugin-name >>_unicode.dll (x86)
                path: << pipeline.parameters.plugin-name >>_win32.zip
                destination: << pipeline.parameters.plugin-name >>_win32.zip
            - store_artifacts:
                name: Upload << pipeline.parameters.plugin-name >>s.dll (x64)
                path: << pipeline.parameters.plugin-name >>_x64.zip
                destination: << pipeline.parameters.plugin-name >>_x64.zip
            - store_artifacts:
                name: Upload << pipeline.parameters.plugin-name >>s.dll (ARM64)
                path: << pipeline.parameters.plugin-name >>_arm64.zip
                destination: << pipeline.parameters.plugin-name >>_arm64.zip
      - persist_to_workspace:
          root: .
          paths: out

  push-release:
    <<: *executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          name: Upload << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>.zip
          path: out/<< pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>.zip
          destination: << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>.zip
      - store_artifacts:
          name: Upload << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
          path: out/<< pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
          destination: << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
      - store_artifacts:
          name: Upload << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_arm64.zip
          path: out/<< pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_arm64.zip
          destination: << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_arm64.zip
      - run:
          name: Create Release
          command: |-
            bash .circleci/scripts/bb_release.sh
            bash .circleci/scripts/gh_release.sh
          shell: bash.exe
          environment:
            SLUGX86: << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>.zip
            SLUGX64: << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
            SLUGARM64: << pipeline.parameters.plugin-name >>_<< pipeline.git.tag >>_arm64.zip
            BIN_DIR: out

workflows:
  cmake:
    jobs:
      - build:
          <<: *development
      - push-release:
          <<: *production
          requires: [build]
