version: 2.1
#
# Copyright (c) 2023 Robert Di Pardo <dipardo.r@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
#
orbs:
  lazarus: rdipardo/lazarus@2
  win: circleci/windows@5

references:
  executor: &executor
    executor:
      name: win/default
      shell: bash.exe
  development: &development
    filters:
      tags:
        only: /v.*/
  production: &production
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /v.*/

jobs:
  push-release:
    <<: *executor
    environment:
      UPX_VER: 4.2.1
    parameters:
      plugin-name:
        type: string
        default: HTMLTag
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install UPX
          command: |
            curl -sLO "https://github.com/upx/upx/releases/download/v$UPX_VER/upx-$UPX_VER-win64.zip"
            7z e upx-$UPX_VER-win64.zip -o"$WINDIR"
            upx.exe --version
      - run:
         name: Build and Pack
         command: make_release.cmd
         shell: cmd.exe
      - store_artifacts:
          name: Upload << parameters.plugin-name >>_<< pipeline.git.tag >>.zip
          path: out/<< parameters.plugin-name >>_<< pipeline.git.tag >>.zip
          destination: << parameters.plugin-name >>_<< pipeline.git.tag >>.zip
      - store_artifacts:
          name: Upload << parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
          path: out/<< parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
          destination: << parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
      - run:
          name: Create Release
          command: |-
            bash .circleci/scripts/bb_release.sh
            bash .circleci/scripts/gh_release.sh
          shell: bash.exe
          environment:
            SLUGX86: << parameters.plugin-name >>_<< pipeline.git.tag >>.zip
            SLUGX64: << parameters.plugin-name >>_<< pipeline.git.tag >>_x64.zip
            BIN_DIR: out

workflows:
  lazarus-build:
    jobs:
      - lazarus/build-win:
          project: HTMLTag
          project-dir: src/prj
          bin-dir: out
          build-type: Debug
          cross-build: true
          <<: *development
      - push-release:
          <<: *production
          requires: [lazarus/build-win]
