#
# SPDX-FileCopyrightText: (c) 2025 Robert Di Pardo <dipardo.r@gmail.com>
# SPDX-License-Identifier: MPL-2.0
#
name: MSVC
on:
  pull_request:
  push:
    tags:
      - '**'
    branches-ignore:
      - 'objpas'
      - 'dependabot/**'

permissions:
  contents: read

jobs:
  build:
    name: 'Build project with MSVC'
    runs-on: windows-2022
    strategy:
      matrix:
        target: [x86, x64, amd64_arm64]
    env:
      TARGETS: |
        { "x64": "x64",
          "x86": "x86",
          "amd64_arm64": "arm64" }
    outputs:
      x64_filehash:   ${{ steps.artifacts.outputs.x64_filehash }}
      x86_filehash:   ${{ steps.artifacts.outputs.x86_filehash }}
      arm64_filehash: ${{ steps.artifacts.outputs.arm64_filehash }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set up MSVC
      uses: TheMrMilchmann/setup-msvc-dev@79dac248aac9d0059f86eae9d8b5bfab4e95e97c # v4.0.0
      with:
        arch: ${{ matrix.target }}
        sdk: '10.0.17763.0'    

    - name: Build
      env:
        PLATFORM: ${{ fromJSON(env.TARGETS)[matrix.target] }}
      run: .\build.cmd Release ${env:PLATFORM} clean nmake

    # https://fossil.2of4.net/npp_htmltag/doc/trunk/doc/HTMLTag-readme.txt
    - name: HTMLTag.dll -> HTMLTag_unicode.dll
      if: matrix.target == 'x86'
      run: mv -Force .\HTMLTag.dll .\HTMLTag_unicode.dll
      working-directory: out/${{ matrix.target }}/Release

    - name: Copy build artifacts
      id: artifacts
      env:
        PLATFORM: ${{ fromJSON(env.TARGETS)[matrix.target] }}
      run: |
        $hash = $(Get-FileHash -A SHA256 .\out\${env:PLATFORM}\Release\*.dll).Hash
        echo "${env:PLATFORM}_filehash=${hash}" >> "${env:GITHUB_OUTPUT}"
        xcopy /DVY .\out\${env:PLATFORM}\Release\*.dll ".\out"
        xcopy /DVY .\dat\*.ini ".\out"
        xcopy /DIY .\*.textile ".\out\Doc"

    - name: Upload HTMLTag-${{ github.run_id }}-${{ env.PLATFORM }}
      env:
        PLATFORM: ${{ fromJSON(env.TARGETS)[matrix.target] }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: HTMLTag-${{ github.run_id }}-${{ env.PLATFORM }}
        path: |
          out/*.dll
          out/*.ini
          out/Doc/

  push_release:
    name: 'Publish new release'
    if: ${{ contains(github.ref, 'tags') && github.event_name == 'push' }}
    needs: build
    concurrency:
      group: rel-${{ github.ref_name }}
      cancel-in-progress: true
    runs-on: ubuntu-slim
    permissions:
      contents: write # required by softprops/action-gh-release
    env:
      SLUGX86: HTMLTag_${{ github.ref_name }}.zip
      SLUGX64: HTMLTag_${{ github.ref_name }}_x64.zip
      SLUGARM64: HTMLTag_${{ github.ref_name }}_arm64.zip
      SHA256X86: ${{ needs.build.outputs.x86_filehash }}
      SHA256X64: ${{ needs.build.outputs.x64_filehash }}
      SHA256ARM64: ${{ needs.build.outputs.arm64_filehash }}
    steps:
    - name: Fetch release artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: bin

    - name: Pack release artifacts
      working-directory: bin
      run: |
        FILEHASH=
        ZIPBALL=
        BINDIRS=('x86' 'x64' 'arm64')
        for d in "${BINDIRS[@]}";
        do
          case "$d" in
            'x86')   ZIPBALL="${SLUGX86}"; FILEHASH="${SHA256X86}" ;;
            'x64')   ZIPBALL="${SLUGX64}"; FILEHASH="${SHA256X64}" ;;
            'arm64') ZIPBALL="${SLUGARM64}"; FILEHASH="${SHA256ARM64}" ;;
          esac
          pushd ./*-${d}/ 2>&1 >/dev/null || exit 1
          # ensure binary artifacts are the same ones we built
          echo $FILEHASH *HTMLTag*.dll | sha256sum -c --quiet
          zip "../${ZIPBALL}" ./Doc ./Doc/* ./*.{ini,dll}
          popd 2>&1 >/dev/null
        done

    - name: Generate release notes
      working-directory: bin
      run: |
        ASSETS=("${SLUGX86}" "${SLUGX64}" "${SLUGARM64}")
        printf '#### SHA256 Checksums\n\n' > release_notes.txt
        for slug in "${ASSETS[@]}"; do printf '\t%s\n' "$(sha256sum -b "$slug")" >> release_notes.txt; done

    - name: Push release
      uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
      with:
        name: ${{ github.ref_name }}
        body_path: bin/release_notes.txt
        fail_on_unmatched_files: true
        files: bin/*.zip
